### ISSUE TITLE
ASWのアイコンにサービス名が出るようにしたい

### ISSUE THREAD

**Issue by tokidrill** [kamiazya/rediagram#111]
**Is your feature request related to a problem? Please describe.**
AWSに詳しくない顧客やメンバーと会話する際に、AWSのアイコンがどのサービスを指しているのかわかりずらい

**Describe the solution you'd like**
AWSのアイコンにサービス名を出せるようにすること

**Comment by kamiazya** [comment]
I want the official design guidelines to be correct, so we'll optionally allow you to choose whether or not to label the service name.

> 公式のデザインガイドラインを正にしたいので、オプションでサービス名のラベルを付与するかどうか選択できるようにしようと思います。

**Comment by kamiazya** [comment]
@all-contributors please add @tokidrill for ideas
