### ISSUE TITLE
If upstream and downstream are mixed, the orientation is incorrect.

### ISSUE THREAD

**Issue by fealone** [kamiazya/rediagram#145]
**Describe the bug**
If upstream and downstream are mixed, the orientation described earlier has priority.

* Example code

```html
<AppEngine
    name="ExampleA"
    upstream={["ExampleB"]}
    downstream={["ExampleB"]}
/>
```

* Expected diagram

`ExampleA` -> `ExampleB`  
`ExampleA` <- `ExampleB`

* Actual diagram

`ExampleA` -> `ExampleB`  
`ExampleA` -> `ExampleB`

**Comment by kamiazya** [comment]
In the current implementation, the direction of the downstream arrow is semantically incorrect.

To solve this problem, we have to make changes that make the drawing backward incompatible.

Also, to maintain functional compatibility, it is necessary to have an option to specify the placement when specifying downstream or upstream.

The option to allow bidirectional resolution resolves #144.
